-- Create Bilduma table
CREATE TABLE IF NOT EXISTS Bilduma (
    id BIGINT PRIMARY KEY NOT NULL,
    chat_id UUID,
    name VARCHAR(255) NOT NULL,
    title TEXT,
    summary TEXT,
    create_date DATE NOT NULL,
    update_date DATE NOT NULL
);

-- Create Fitxategia table
CREATE TABLE IF NOT EXISTS Fitxategia (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    text TEXT,
    charNum INTEGER,
    format VARCHAR(10) CHECK (format IN ('PDF', 'TXT', 'DOC', 'DOCX', 'SRT')),
    bilduma_key BIGINT REFERENCES Bilduma(id) ON DELETE CASCADE
);

-- Create Fitxategia table
CREATE TABLE IF NOT EXISTS Note (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status_ready BOOLEAN DEFAULT FALSE,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(10) CHECK (type IN ('summary', 'outline', 'glossary', 'FAQ', 'timeline', 'mindmap')),
    content TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    bilduma_key BIGINT REFERENCES Bilduma(id) ON DELETE CASCADE
);

-- Create Document table
CREATE TABLE IF NOT EXISTS Document (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content TEXT NOT NULL,
    embedding FLOAT8[] NOT NULL,
    start_index INTEGER NOT NULL,
    file_id BIGINT NOT NULL REFERENCES Fitxategia (id) ON DELETE CASCADE
);